CREATE DATABASE IF NOT EXISTS `aws_db` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `aws_db`;

CREATE TABLE IF NOT EXISTS `teste` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `teste` varchar(255) NOT NULL,
  `createad_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO teste (teste) VALUES
('Abacaxi'),
('Banana'),
('Cachorro'),
('Dedo'),
('Elefante'),
('Futebol'),
('Girafa'),
('Hipopótamo'),
('Iguana'),
('Jardim'),
('Kiwi'),
('Limão'),
('Morango'),
('Nuvem'),
('Oceano'),
('Pizza'),
('Queijo'),
('Rato'),
('Sol'),
('Tigre'),
('Uva'),
('Vento'),
('Xícara'),
('Yoga'),
('Zebra'),
('Amarelo'),
('Branco'),
('Cinza'),
('Dourado'),
('Esmeralda'),
('Fogo'),
('Gelo'),
('Hortênsia'),
('Índigo'),
('Jade'),
('Ketchup'),
('Lavanda'),
('Magenta'),
('Noz'),
('Orquídea'),
('Pêssego'),
('Quartzo'),
('Rosa'),
('Safira'),
('Tangerina'),
('Urano'),
('Verde'),
('Waffle'),
('Xadrez'),
('Basquete'),
('Azul'),
('Bola'),
('Cama'),
('Dado'),
('Escada'),
('Flor'),
('Gato'),
('Hotel'),
('Igreja'),
('Janela'),
('Koala'),
('Lua'),
('Montanha'),
('Navio'),
('Óculos'),
('Porta'),
('Quarto'),
('Relógio'),
('Sapato'),
('Telefone'),
('Unha'),
('Violão'),
('Whisky'),
('Xilofone'),
(' iogurte '),
('Árvore'),
('Biscoito'),
('Copo'),
('Dinheiro'),
('Escova'),
('Faca'),
('Garfo'),
('Helicóptero'),
('Internet'),
('Jipe'),
('Lápis'),
('Mesa'),
('Notebook'),
('Ovo'),
('Prato'),
('Quebra-cabeça'),
('Rua'),
('Sofá'),
('Televisão'),
('Uniforme'),
('Vaso'),
('Xampu'),
('Youtube'),
('Zoológico');